spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    driverClassName: com.mysql.cj.jdbc.Driver
    username: user
    password: password
