spring:
  datasource:
    url: jdbc:h2:mem:cartesian_db
    driverClassName: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        auto_quote_keyword: true
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
